### ISSUE TITLE
Error when carrying out Phylogenetic profiling 

### ISSUE THREAD

**Issue by Dearbhaile** [zhaotao1987/Syn-MRL#2]
Hi Dr.Zhao, 

I have run into an error when I am carrying out the Phylogenetic profiling of the pipeline. I am using 94 ecdyzosoan genomes and am getting this error:

Loading required package: permute
Loading required package: lattice
This is vegan 2.5-7
_**Error in hclust(d, method = "ward.D") : 
  size cannot be NA nor exceed 65536
Execution halted**_

Could you help me overcome this?

All the best, 
Dearbhaile.

**Comment by zhaotao1987** [comment]
Maybe too many clusters, which vegan cannot handle.. Maybe try transpose the matrix and try? 
Or maybe filter the clusters by some criteria beforehand.
