### ISSUE TITLE
Do you have a tutorial on how to run SYN-MRL after you have the Synteny Network file?

### ISSUE THREAD

**Issue by ank-man** [zhaotao1987/Syn-MRL#3]
I am done with running the SyntneyNet but it gives me error saying while running infomap clustering
Infomap SynNetformatted.txt Clustering/ --clu -N 10 -2 --flow-model undirected
=======================================================
  Infomap v1.4.1 starts at 2023-10-19 14:37:23
  -> Input network: SynNetformatted.txt
  -> Output path:   Clustering/
  -> Configuration: clu
                    two-level
                    flow-model = undirected
                    num-trials = 10
=======================================================
  OpenMP 201511 detected with 32 threads...
Parsing undirected network from file 'SynNetformatted.txt'...
  Parsing links...
'rror: Can't parse link data from line 'PGAS1623       PGNA1056    700

**Comment by zhaotao1987** [comment]
please check this: https://github.com/zhaotao1987/SynNet-Pipeline/wiki/Syn_MRL
